include:
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: pro_micro_i2c
    shield: sweep_central_dongle dongle_display
